language: node_js
services:
  - docker
cache:
  directories:
    - ~/.npm
node_js:
  - '18'
git:
  depth: 3
script:
  - yarn test
  - yarn build
  - yard test
  - docker build . -t=javascript-data-structure-kata:travis-build-$TRAVIS_BUILD_NUMBER
on:
  branch: develop 